---
hide_body: false
fields:
- name: banner_image
  label: Banner Image
  type: file
  description: Dimensions work best at 1200 pixels by 400 pixels
  hidden: false
  default: ''
- type: text
  name: title
  label: Title
- type: datetime
  name: date
  label: Date
- type: select
  name: color
  config:
    source:
      type: simple
    options:
    - White Bg
    - Red Bg
    - Green Bg
    - Orange Bg
  label: Sub Category
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default: []
- name: slug
  label: Slug
  type: text
  hidden: false
  default: ''
- type: field_group_list
  name: gallery
  label: Gallery
  fields:
  - type: file
    name: image
    label: Image
  - type: text
    label: Caption
    name: caption
- type: list
  name: tech
  label: Tech
